const pages = [
  { title: "About", url: "about.html", keywords: "about cheese is life website information" },
  { title: "American", url: "american.html", keywords: "american cheese processed slices burger sandwich" },
  { title: "Babybel", url: "babybel.html", keywords: "babybel mini wax snack cheese" },
  { title: "Blue Stilton", url: "bluestilton.html", keywords: "blue stilton british strong mold cheese" },
  { title: "Boursin", url: "boursin.html", keywords: "boursin french garlic herb soft cheese" },
  { title: "Brie", url: "brie.html", keywords: "brie soft french creamy white rind cheese" },
  { title: "Burrata", url: "burrata.html", keywords: "burrata italian creamy mozzarella center cheese" },
  { title: "Camembert", url: "camembert.html", keywords: "camembert french soft bloomy rind cheese" },
  { title: "Cheddar", url: "cheddar.html", keywords: "cheddar yellow sharp aged english cheese" },
  { title: "Cheshire", url: "cheshire.html", keywords: "cheshire british crumbly mild cheese" },
  { title: "Colby Jack", url: "colbyjack.html", keywords: "colby jack marbled american mild cheese" },
  { title: "Contact", url: "contact.html", keywords: "contact page email cheese is life" },
  { title: "Cotija", url: "cotija.html", keywords: "cotija mexican salty crumbly cheese" },
  { title: "Cottage", url: "cottage.html", keywords: "cottage cheese fresh curds healthy protein" },
  { title: "Cream Cheese", url: "cream.html", keywords: "cream cheese spread bagel soft fresh" },
  { title: "Double Gloucester", url: "doublegloucester.html", keywords: "double gloucester english hard cheese" },
  { title: "Edam", url: "edam.html", keywords: "edam dutch semi hard red wax cheese" },
  { title: "Emmental", url: "emmental.html", keywords: "emmental swiss holes nutty cheese" },
  { title: "Feta", url: "feta.html", keywords: "feta greek salty brined white cheese" },
  { title: "Fontina", url: "fontina.html", keywords: "fontina italian melting cheese fondue" },
  { title: "Fromage Blanc", url: "fromageblanc.html", keywords: "fromage blanc french fresh soft cheese" },
  { title: "Gouda", url: "gouda.html", keywords: "gouda dutch sweet nutty cheese" },
  { title: "Gorgonzola", url: "gorgonzola.html", keywords: "gorgonzola italian blue strong cheese" },
  { title: "Grana Padano", url: "granapadano.html", keywords: "grana padano italian hard parmesan style cheese" },
  { title: "Halloumi", url: "halloumi.html", keywords: "halloumi cyprus grilling squeaky cheese" },
  { title: "Havarti", url: "havarti.html", keywords: "havarti danish creamy semi soft cheese" },
  { title: "Kasseri", url: "kasseri.html", keywords: "kasseri greek semi hard cheese" },
  { title: "Le Gruyère", url: "legruyere.html", keywords: "gruyere swiss nutty firm cheese fondue" },
  { title: "Limburger", url: "limburger.html", keywords: "limburger strong smell soft cheese" },
  { title: "Manchego", url: "manchego.html", keywords: "manchego spanish sheep milk cheese" },
  { title: "Monterey Jack", url: "montereyjack.html", keywords: "monterey jack american mild melting cheese" },
  { title: "Neufchâtel", url: "neufchatel.html", keywords: "neufchatel french soft cheese similar brie" },
  { title: "Paneer", url: "paneer.html", keywords: "paneer indian fresh cheese curry" },
  { title: "Pecorino", url: "pecorino.html", keywords: "pecorino italian sheep milk hard cheese" },
  { title: "Pecorino Sardo", url: "pecorinosardo.html", keywords: "pecorino sardo sardinian sheep cheese" },
  { title: "Pecorino Toscano", url: "pecorinotoscano.html", keywords: "pecorino toscano tuscan sheep cheese" },
  { title: "Pepper Jack", url: "pepperjack.html", keywords: "pepper jack spicy chili american cheese" },
  { title: "Parmesan", url: "perm.html", keywords: "parmesan parmigiano reggiano italian hard cheese" },
  { title: "Provolone", url: "provolone.html", keywords: "provolone italian semi hard cheese sandwich" },
  { title: "Queso Fresco", url: "quesofresco.html", keywords: "queso fresco mexican fresh cheese" },
  { title: "Queso Oaxaca", url: "quesooaxaca.html", keywords: "queso oaxaca mexican string cheese" },
  { title: "Raclette", url: "raclette.html", keywords: "raclette swiss melting cheese" },
  { title: "Reblochon", url: "reblochon.html", keywords: "reblochon french soft washed rind cheese" },
  { title: "Ricotta", url: "ricotta.html", keywords: "ricotta italian fresh soft cheese" },
  { title: "Roquefort", url: "roquefort.html", keywords: "roquefort french blue strong cheese" },
  { title: "Saint André", url: "saintandre.html", keywords: "saint andre french triple cream cheese" },
  { title: "Swiss", url: "swiss.html", keywords: "swiss cheese holes nutty mild" },
  { title: "Taleggio", url: "taleggio.html", keywords: "taleggio italian washed rind cheese" }
];